### ISSUE TITLE
Bug lors du build npm

### ISSUE THREAD

**Issue by Tharyrok** [LgHS/Site-Web-Front#10]
npm ERR! Linux 4.5.0-0.bpo.1-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "lghs-website"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code E404

npm ERR! 404 Not Found: lghs-website
npm ERR! 404 
npm ERR! 404 'lghs-website' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tharyrok/devlopement/Site-Web-Front/npm-debug.log

**Comment by drskullster** [comment]
ça doit être lié à ansible qui essaie d'installer le paquet défini dans package.json. 

Est-ce que le bug est présent quand tu buildes "à la main" ?

**Comment by Tharyrok** [comment]
C'est en local sur mon pc

Voici une sortie plus complète : 

```
> lghs-website@1.0.0 postinstall /home/tharyrok/devlopement/Site-Web-Front
> npm run build


> lghs-website@1.0.0 build /home/tharyrok/devlopement/Site-Web-Front
> npm run scss && npm run svg && npm run img && npm run favicon && npm run fa:copy-fonts


> lghs-website@1.0.0 scss /home/tharyrok/devlopement/Site-Web-Front
> node-sass --output-style compressed -o files/dist/css src/assets/scss

Rendering Complete, saving .css file...
Wrote CSS to /home/tharyrok/devlopement/Site-Web-Front/files/dist/css/main.css
Wrote 1 CSS files to /home/tharyrok/devlopement/Site-Web-Front/files/dist/css

> lghs-website@1.0.0 svg /home/tharyrok/devlopement/Site-Web-Front
> svgo -f src/assets/svg -o files/dist/svg

Processing directory 'src/assets/svg':

logo.svg:
Done in 59 ms!
17.745 KiB - 51.2% = 8.653 KiB

tooth.svg:
Done in 17 ms!
4.114 KiB - 65.8% = 1.406 KiB


> lghs-website@1.0.0 img /home/tharyrok/devlopement/Site-Web-Front
> imagemin src/assets/images files/dist/images -p


> lghs-website@1.0.0 favicon /home/tharyrok/devlopement/Site-Web-Front
> npm run favicon:generate && npm run favicon:inject


> lghs-website@1.0.0 favicon:generate /home/tharyrok/devlopement/Site-Web-Front
> real-favicon generate favicon-config.json favicon-data.json files/

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src/favicon/favicon.png'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.exports.fileToBase64Sync (/home/tharyrok/devlopement/Site-Web-Front/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:35:15)
    at Object.exports.normalizeMasterPicture (/home/tharyrok/devlopement/Site-Web-Front/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:202:45)
    at Object.exports.createRequest (/home/tharyrok/devlopement/Site-Web-Front/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:243:38)
    at /home/tharyrok/devlopement/Site-Web-Front/node_modules/cli-real-favicon/real-favicon-generate.js:32:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

npm ERR! Linux 4.5.0-0.bpo.1-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "favicon:generate"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! lghs-website@1.0.0 favicon:generate: `real-favicon generate favicon-config.json favicon-data.json files/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lghs-website@1.0.0 favicon:generate script 'real-favicon generate favicon-config.json favicon-data.json files/'.
npm ERR! This is most likely a problem with the lghs-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     real-favicon generate favicon-config.json favicon-data.json files/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lghs-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lghs-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tharyrok/devlopement/Site-Web-Front/npm-debug.log

npm ERR! Linux 4.5.0-0.bpo.1-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "favicon"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! lghs-website@1.0.0 favicon: `npm run favicon:generate && npm run favicon:inject`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lghs-website@1.0.0 favicon script 'npm run favicon:generate && npm run favicon:inject'.
npm ERR! This is most likely a problem with the lghs-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run favicon:generate && npm run favicon:inject
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lghs-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lghs-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tharyrok/devlopement/Site-Web-Front/npm-debug.log

npm ERR! Linux 4.5.0-0.bpo.1-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! lghs-website@1.0.0 build: `npm run scss && npm run svg && npm run img && npm run favicon && npm run fa:copy-fonts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lghs-website@1.0.0 build script 'npm run scss && npm run svg && npm run img && npm run favicon && npm run fa:copy-fonts'.
npm ERR! This is most likely a problem with the lghs-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run scss && npm run svg && npm run img && npm run favicon && npm run fa:copy-fonts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lghs-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lghs-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tharyrok/devlopement/Site-Web-Front/npm-debug.log

npm ERR! Linux 4.5.0-0.bpo.1-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! lghs-website@1.0.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lghs-website@1.0.0 postinstall script 'npm run build'.
npm ERR! This is most likely a problem with the lghs-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lghs-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lghs-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tharyrok/devlopement/Site-Web-Front/npm-debug.log
```

**Comment by drskullster** [comment]
OK, j'arrive à reproduire.
